language: node_js
jobs:
  include:
    - stage: lint
      node_js: 8
      script: npm run lint
    - stage: test
      node_js:
        - 6
        - 7
        - 8
        - 9
        - 10
      script:
        - npm run travis
      after_script:
        - npm run report-coverage
