language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
  - 10
script:
  - npm run test
jobs:
  include:
    - stage: lint
      node_js: 8
      script: npm run lint
    - stage: coverage
      node_js: 8
      script: npm run travis
      after_script:
        - npm run report-coverage
